defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  
# Hydra config
hydra:
  run:
    dir: ./outputs/exp_${hydra.job.override_dirname}


# Automatically load from the last checkpoint
checkpoint: True
restart: False # Ignore existing checkopoints
checkpoint_file: checkpoint.th
history_file: history.json

seed: 2077
verbose: 0
# Optimization 
optim: adam
lr: 5e-4
beta2: 0.999

epochs: 1
batch_size: 128

# learning rate scheduling
lr_sched: step # can be either step or plateau
step: 
  step_size: 2
  gamma: 0.98
plateau:
  factor: 0.5
  patience: 5
